name: Playwright Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
          - all

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install Playwright browsers
        run: |
          mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Create directories for artifacts
        run: |
          mkdir -p target/screenshots
          mkdir -p target/videos
          mkdir -p target/traces
          mkdir -p target/allure-results

      - name: Run smoke tests
        if: github.event_name == 'push' || github.event.inputs.test_suite == 'smoke'
        run: |
          mvn test -Dbrowser=${{ matrix.browser }} -Dheadless=true -Dgroups=smoke
        continue-on-error: true

      - name: Run regression tests
        if: github.event_name == 'schedule' || github.event.inputs.test_suite == 'regression'
        run: |
          mvn test -Dbrowser=${{ matrix.browser }} -Dheadless=true -Dgroups=regression
        continue-on-error: true

      - name: Run all tests
        if: github.event.inputs.test_suite == 'all'
        run: |
          mvn test -Dbrowser=${{ matrix.browser }} -Dheadless=true
        continue-on-error: true

      - name: Generate Allure Report
        if: always()
        run: |
          mvn allure:report

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.browser }}
          path: |
            target/screenshots/
            target/videos/
            target/traces/
            target/surefire-reports/
            target/allure-results/
            target/site/allure-maven-plugin/
          retention-days: 30

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: target/allure-results/
          retention-days: 30

  publish-report:
    name: Publish Test Report
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge Allure Results
        run: |
          mkdir -p merged-results
          find artifacts -name "allure-results*" -type d -exec cp -r {}/* merged-results/ \; 2>/dev/null || true

      - name: Generate Combined Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: merged-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
          keep_reports: 20

      - name: Publish to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages